# Generated by Django 5.1.6 on 2025-03-06 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_rename_coleta_transporte_coleta_quantidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='data_venda',
            field=models.DateField(),
        ),
    ]
